### ISSUE TITLE
Resizing columns in a fixed width table

### ISSUE THREAD

**Issue by jackdeguest** [irhc/table-drag-sort-resize#1]
Let me first congratulate you on your fine achievement in combining 3 key features. Excellent job! The first one I saw around like that.
So, everythign is working just fine, except that I would like to be able to resize columns while keeping the overall table width. Thus a column should gain/lose width to the detriment or benefit of another one.
I have looked at your code, but with lack of documentation, I am not sure what to change.
Could you implement this option?

Thanks,
Jacques

**Comment by ckprod** [comment]
Hi, Jacques,

Thank you. Im happy someone can make use of it.

Yes, no problem. It requires some new logic, but in general, it should not be too complicated. I will commit a new version in the next few days.

Von: Jacques Deguest [mailto:notifications@github.com] 
Gesendet: Freitag, 30. Jänner 2015 06:36
An: irhc/table-drag-sort-resize
Betreff: [table-drag-sort-resize] Resizing columns in a fixed width table (#1)

Let me first congratulate you on your fine achievement in combining 3 key features. Excellent job! The first one I saw around like that.
So, everythign is working just fine, except that I would like to be able to resize columns while keeping the overall table width. Thus a column should gain/lose width to the detriment or benefit of another one.
I have looked at your code, but with lack of documentation, I am not sure what to change.
Could you implement this option?

Thanks,
Jacques

**Comment by jackdeguest** [comment]
Danke sehr ! I am looking forward to the updated release !

**Comment by ckprod** [comment]
Gern' geschehen! You're welcome!

Version 1.1 out.

**Comment by jackdeguest** [comment]
Thank you very much! However, I could not see any updated version released. Can you please double check or point me to it?

**Comment by jackdeguest** [comment]
Thank you very much! However, I could not see any updated version released. Can you please double check or point me to it?

**Comment by jackdeguest** [comment]
Thank you very much! However, I could not see any updated version released. Can you please double check or point me to it?
